swagger: "2.0"
info:
  title: httpbin.org
  description: A simple HTTP Request & Response Service.
  version: 0.0.1
host: localhost:8080
schemes:
  http
basePath: /
produces:
  application/json
paths:
  /get:
    get:
      summary: The Requests Parameters
      tags:
        - HTTP Methods
      responses:
        "200":
          description: The request parameters
  /delete:
    delete:
      summary: The request's DELETE parameters.
      tags:
        - HTTP Methods
      responses:
        "200":
          description: The request's DELETE parameters.
  /patch:
    patch:
      produces:
        - application/json
      responses:
        '200':
          description: The request's PATCH parameters.
      summary: The request's PATCH parameters.
      tags:
        - HTTP Methods
  /post:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: The request's POST parameters.
      summary: The request's POST parameters.
      tags:
        - HTTP Methods
  /put:
    put:
      produces:
        - application/json
      responses:
        '200':
          description: The request's PUT parameters.
      summary: The request's PUT parameters.
      tags:
        - HTTP Methods
  /image:
    get:
      produces:
        - image/webp
        - image/svg+xml
        - image/jpeg
        - image/png
        - image/gif
        - image/*
      responses:
        '200':
          description: An image.
      summary: Returns a simple image of the type suggest by the Accept header.
      tags:
        - Images
  /image/jpeg:
    get:
      produces:
        - image/jpeg
      responses:
        '200':
          description: A JPEG image.
      summary: Returns a simple JPEG image.
      tags:
        - Images
  /image/png:
    get:
      produces:
        - image/png
      responses:
        '200':
          description: A PNG image.
      summary: Returns a simple PNG image.
      tags:
        - Images
  /image/gif:
    get:
      produces:
        - image/gif
      responses:
        '200':
          description: An GIF image.
      summary: Returns a simple GIF image.
      tags:
        - Images
  /image/svg:
    get:
      produces:
        - image/svg+xml
      responses:
        '200':
          description: An SVG image.
      summary: Returns a simple SVG image.
      tags:
        - Images
  /image/webp:
    get:
      produces:
        - image/webp
      responses:
        '200':
          description: A WEBP image.
      summary: Returns a simple WEBP image.
      tags:
        - Images
  /redirect-to:
    delete:
      produces:
        - text/html
      responses:
        '404':
          description: Redirect to donn't support delete, because it does not has parameter url.
      summary: 404 Not Found
      tags:
        - Redirects
    get:
      parameters:
        - in: query
          name: url
          required: true
          type: string
        - in: query
          name: status_code
          type: int
      produces:
        - text/html
      responses:
        '302':
          description: A redirection.
      summary: 302/3XX Redirects to the given URL.
      tags:
        - Redirects
    post:
      parameters:
        - in: formData
          name: url
          required: true
          type: string
        - in: formData
          name: status_code
          required: false
          type: int
      produces:
        - text/html
      responses:
        '302':
          description: A redirection.
      summary: 302/3XX Redirects to the given URL.
      tags:
        - Redirects
    patch:
      parameters:
        - in: formData
          name: url
          required: true
          type: string
        - in: formData
          name: status_code
          required: false
          type: int
      produces:
        - text/html
      responses:
        '302':
          description: A redirection.
      summary: 302/3XX Redirects to the given URL.
      tags:
        - Redirects
    put:
      parameters:
        - in: formData
          name: url
          required: true
          type: string
        - in: formData
          name: status_code
          required: false
          type: int
      produces:
        - text/html
      responses:
        '302':
          description: A redirection.
      summary: 302/3XX Redirects to the given URL.
      tags:
        - Redirects
  /headers:
    get:
      responses:
        '200':
          description: The request's headers
      summary: Return the incoming request's HTTP Headers
      tags:
        - Request Inspection
  /ip:
    get:
      responses:
        '200':
          description: The request's IP Address
      summary: Returns the incoming request's IP Address
      tags:
        - Request Inspection
  /user-agent:
    get:
      responses:
        '200':
          description: The request's User-Agent Header
      summary: Returns the incoming request's User-Agent Header
      tags:
        - Request Inspection
  /base64/{value}:
    get:
      parameters:
        - default: TG92ZSBHb2xhbmcK
          in: path
          name: value
          type: string
      produces:
        - text/html
      responses:
        '200':
          description: Decoded base64 content.
      summary: Decodes base64url-encoded string.
      tags:
        - Dynamic data
  /uuid:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: A UUID4.
      summary: Return a UUID4.
      tags:
        - Dynamic data
  '/bytes/{n}':
    get:
      parameters:
        - in: path
          name: 'n'
          type: int
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Bytes.
      summary: Returns n random bytes generated with given seed
      tags:
        - Dynamic data
  /stream-bytes/{n}:
    get:
      parameters:
        - in: path
          name: 'n'
          type: int
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Bytes.
      summary: 'Streams n random bytes generated with given seed, at given chunk size per packet.'
      tags:
        - Dynamic data
